words_in_u4 = [
    ("hacker        ","黑客"),
    ("literal       ","字面上的"),
    ("compliment    ","赞美"),
    ("offense       ","冒犯"),
    ("gradual       ","逐渐的，逐步的"),
    ("brilliantly   ","很，极其"),
    ("predate       ","先于"),
    ("entertain     ","招待，使有兴趣"),
    ("kit           ","工具包"),
    ("investigative ","调查的，调查性质的"),
    ("motive        ","动机"),
    ("revenge       ","复仇"),
    ("disobedience  ","不服从，违抗"),
    ("byproduct     ","副产品"),
    ("distinguished ","卓越的"),
    ("version       ","版本"),
    ("poser         ","装腔作势的人"),
    ("net           ","纯的"),
    ("notorious     ","臭名昭著的"),
    ("copyright     ","版权"),
    ("cooperate     ","合作"),
    ("excessively   ","过分的"),
    ("impose        ","强制实行"),
    ("cloud         ","使不清晰，不明朗"),
    ("hrash         ","严厉的"),
    ("violently     ","猛烈的"),
    ("legislator    ","立法者"),
    ("squawk        ","发出刺耳的声音"),
    ("rebellious    ","反叛"),
    ("seem forign in","陌生的"),
    ("factor in     ","包括，把。。。计算在内"),
    ("poke about    ","到处寻找，闲逛，窥探"),
    ("more often than not","多半"),
    ("go off        ","动身"),
    ("take apart    ","拆卸"),
    ("by definition ","根据定义"),
    ("be opposed to ","反对"),
    ("intend to     ","打算")
]